### ISSUE TITLE
Uncaught TypeError: self.swipe.dispatch is not a function

### ISSUE THREAD

**Issue by jjjachyty** [Muxi-Studio/vue-finger#2]
i was use v-finger:swipe="this.bar" ,the console print error

**Comment by zxc0328** [comment]
你用的npm install安装的吗 npm里那个vue-finger是https://github.com/gggso/vue-finger 这个 我们这个还没放到NPM上

**Comment by jjjachyty** [comment]
嗯 我看了下代码说明才发现不是这个 不好意思
